<testsuite name="login.Successful Login" tests="2" errors="0" failures="0" skipped="0" time="5.788255" timestamp="2024-04-13T15:54:30.262123" hostname="DESKTOP-98VP8H0"><testcase classname="login.Successful Login" name="1 Successful Login" status="passed" time="5.077706"><system-out>
<![CDATA[
@scenario.begin
  Scenario: 1 Successful Login
    Given I am on the Demo Login Page ... passed in 3.931s
    When I fill the account information for account StandardUser into the Username field and the Password field ... passed in 0.620s
    And I click the Login Button ... passed in 0.383s
    Then I am redirected to the Demo Main Page ... passed in 0.015s
    And I verify the App Logo exists ... passed in 0.130s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="login.Successful Login" name="Failed Login with LockedOutUser" status="passed" time="0.710549"><system-out>
<![CDATA[
@scenario.begin
  Scenario: Failed Login with LockedOutUser
    Given I am on the Demo Login Page ... passed in 0.159s
    When I fill the account information for account LockedOutUser into the Username field and the Password field ... passed in 0.310s
    And I click the Login Button ... passed in 0.132s
    Then I verify the Error Message contains the text "Sorry, this user has been banned." ... passed in 0.109s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase></testsuite>